# Generated by Django 5.2.13 on 2026-04-27 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='landing', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'waitlist entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
